[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.91.0"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
